import { ArrowUpRight, Code2, FlaskConical, HeartHandshake, Layers3, ShieldAlert } from 'lucide-react';
import { Disclaimer, PageHeading } from '../components/Shell';
import type { Page } from '../types';

export default function About({ onNavigate }: { onNavigate: (page:Page)=>void }) {
  return <div className="page-wrap"><PageHeading eyebrow="ABOUT DR-XAI" title="Research first. Claims kept in scope." description="A model-aware interface for exploring diabetic retinopathy classification research." action={<button className="button button-outline" onClick={()=>onNavigate('Research')}>View methods <ArrowUpRight size={15}/></button>}/>
    <section className="about-hero panel"><div className="about-mark"><FlaskConical size={24}/></div><div><span className="step-label">PROJECT PURPOSE</span><h2>Make an evolving research system easier to inspect.</h2><p>DR-XAI brings retinal image input, standardized model output, research context, and explainability status into one interface. It is a research prototype and decision-support demonstration, not a clinical product.</p></div></section>
    <div className="about-grid"><article className="panel about-card"><span className="about-card-icon"><Layers3 size={18}/></span><span className="step-label">CURRENT MODEL</span><h3>Checkpoint-based inference</h3><p>The existing Flask service loads available PyTorch checkpoints and combines successful predictions through majority voting. The UI consumes a stable prediction response rather than embedding model-specific assumptions.</p><button className="text-link" onClick={()=>onNavigate('Research')}>Model & evaluation <ArrowUpRight size={14}/></button></article><article className="panel about-card"><span className="about-card-icon"><Code2 size={18}/></span><span className="step-label">TECHNOLOGY</span><h3>Replaceable by design</h3><p>React, TypeScript, Vite, and Tailwind CSS power the frontend. Flask remains the inference service, with a documented HTTP boundary for model replacement.</p><div className="tech-chips"><span>React</span><span>TypeScript</span><span>Flask</span><span>PyTorch</span></div></article><article className="panel about-card"><span className="about-card-icon"><HeartHandshake size={18}/></span><span className="step-label">RESEARCH DIRECTION</span><h3>Measure beyond classification</h3><p>Future work includes calibration, explainability evaluation, additional architectures, ensemble assessment, and external validation.</p><button className="text-link" onClick={()=>onNavigate('Research')}>Research roadmap <ArrowUpRight size={14}/></button></article><article className="panel about-card caution-card"><span className="about-card-icon"><ShieldAlert size={18}/></span><span className="step-label">LIMITATIONS & RESPONSIBILITY</span><h3>Not clinically validated</h3><p>Performance varies across severity grades. External validation is not integrated and model calibration remains under investigation. No output should be treated as a medical diagnosis.</p></article></div><Disclaimer/>
  </div>;
}
