import { useState } from 'react';
import { Download, FileCheck2, FileText, Info, Printer } from 'lucide-react';
import { PageHeading, Disclaimer } from '../components/Shell';
import type { ModelPrediction, Page } from '../types';
import { markReportGenerated } from '../services/modelService';

export default function Reports({ result, onNavigate }: { result: ModelPrediction|null; onNavigate: (page:Page)=>void }) {
  const [generated, setGenerated] = useState(false);
  const report = result ? { title: 'DR-XAI Research Analysis Report', analysis_id: result.analysis_id, generatedAt: new Date().toISOString(), analyzedAt: result.created_at, image: 'Uploaded retinal fundus image', prediction: { label: result.class_name, class: result.predicted_class, confidence: result.confidence, probabilities: result.probabilities }, model: { name: result.model_name, version: result.model_version, status: 'Current research baseline' }, explainability: { gradCam: result.explainability?.gradcam_available ? 'Available' : 'Not attached to API response', shap: result.explainability?.shap_available ? 'Available' : 'Not available' }, metricsContext: 'Baseline research metrics are available on the Research page and are not per-image performance measures.', disclaimer: 'Experimental research prototype. Not a medical diagnosis. Not clinically validated. Not a substitute for evaluation by a qualified healthcare professional.' } : null;
  const download = () => { if (!report) return; const url = URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})); const link=document.createElement('a');link.href=url;link.download='dr-xai-research-report.json';link.click();URL.revokeObjectURL(url); };
  const generate = async () => { if (!result) return; try { if (result.analysis_id) await markReportGenerated(result.analysis_id); setGenerated(true); download(); } catch { setGenerated(false); } };
  return <div className="page-wrap"><PageHeading eyebrow="REPORTS" title="A structured research record." description="Generate and download a report containing only the information returned by the model service." action={result ? <button className="button button-primary" onClick={()=>void generate()}><Download size={16}/> Download report</button>:undefined}/>
    {!result ? <section className="empty-results report-empty"><div className="empty-orbit"><FileText size={26}/></div><h2>No analysis is available to report</h2><p>Run an analysis first. Reports do not include invented patient or image details.</p><button className="button button-primary" onClick={()=>onNavigate('Analysis')}>Go to image analysis</button></section> : <div className="report-layout"><section className="panel report-preview"><div className="report-top"><div className="report-file-icon"><FileText size={19}/></div><div><span className="step-label">REPORT PREVIEW</span><h2>Research analysis record</h2></div><span className="report-status"><FileCheck2 size={14}/> {generated?'GENERATED':'READY'}</span></div><div className="report-content"><div className="report-section"><span>01</span><div><h3>Image information</h3><p>Retinal fundus image submitted for research analysis. No patient information was provided.</p></div></div><div className="report-section"><span>02</span><div><h3>AI model prediction</h3><p><strong>{result.class_name}</strong> · Class {result.predicted_class} · Confidence {(result.confidence*100).toFixed(1)}%</p></div></div><div className="report-section"><span>03</span><div><h3>Probability distribution</h3><div className="report-probs">{['No DR','Mild','Moderate','Severe','Proliferative DR'].map((name,i)=><span key={name}>{name}<b>{(result.probabilities[i]*100).toFixed(1)}%</b></span>)}</div></div></div><div className="report-section"><span>04</span><div><h3>Model information</h3><p>{result.model_name} · Version {result.model_version} · Current research baseline</p></div></div><div className="report-section"><span>05</span><div><h3>Explainability</h3><p>{result.explainability?.gradcam_available ? 'Grad-CAM is available for this analysis.' : 'Grad-CAM output is not attached.'} {result.explainability?.shap_available ? 'SHAP is available.' : 'SHAP is planned for a future research release.'}</p></div></div><div className="report-section"><span>06</span><div><h3>Research metrics context</h3><p>Baseline research evaluation metrics are reported separately and are not per-image performance measures.</p></div></div></div><div className="report-disclaimer"><Info size={16}/><p>{report?.disclaimer}</p></div></section><aside className="report-aside"><div className="panel side-panel"><span className="step-label">REPORT ACTIONS</span><h3>Export your record</h3><p className="side-copy">Download a JSON file with the prediction and its model metadata. Patient fields remain absent unless explicitly supplied.</p><button className="button button-primary full-button" onClick={()=>void generate()}><Download size={16}/> Download JSON</button><button className="button button-outline full-button" onClick={()=>window.print()}><Printer size={16}/> Print this view</button></div><div className="report-data-note"><Info size={15}/><span>No patient name, age, or other identity details are collected in this interface.</span></div></aside></div>}
    <Disclaimer compact/>
  </div>;
}
