import { ArrowDown, ArrowUpRight, BrainCircuit, ChartNoAxesCombined, CircleAlert, Database, Layers3, ScanEye, Target } from 'lucide-react';
import { Disclaimer, PageHeading } from '../components/Shell';
import type { Page } from '../types';

const metrics = [['75.92%','Accuracy'],['52.31%','Balanced accuracy'],['53.84%','Macro F1'],['0.6771','Quadratic weighted kappa'],['0.8212','Macro ROC-AUC'],['0.5255','Macro PR-AUC']];
const phases = ['Four-model checkpoint ensemble','Preprocessing comparison','Per-model Grad-CAM','Per-model SHAP','Calibration study','XAI consistency','External validation','Additional architectures','Final research model'];
const classes = ['No DR','Mild','Moderate','Severe','Proliferative DR'];
export default function Research({ onNavigate }: { onNavigate: (page: Page) => void }) {
  return <div className="page-wrap"><PageHeading eyebrow="RESEARCH OVERVIEW" title="A measurable research baseline." description="Methods, evaluation context, and limitations for the current five-class study." action={<button className="button button-outline" onClick={() => onNavigate('About')}>Project context <ArrowUpRight size={15}/></button>}/>
    <section className="research-intro"><div className="research-intro-mark"><Target size={23}/></div><div><span className="step-label">RESEARCH OBJECTIVE</span><h2>Study severity classification with interpretability in view.</h2><p>This project investigates deep-learning classification of diabetic retinopathy severity from retinal fundus images, focusing on ordinal performance, class imbalance, generalization, calibration, and explainability.</p></div><div className="objective-tags"><span>Ordinal learning</span><span>Class imbalance</span><span>Calibration</span><span>Explainability</span></div></section>
    <div className="research-cards"><article className="panel research-detail"><div className="detail-icon"><Database size={18}/></div><span className="step-label">DATASET & SPLIT</span><h3>APTOS 2019</h3><p>Five severity grades with a 70 / 15 / 15 train, validation, and test split. Validation and test data are held apart from training.</p><div className="split-bar"><span/><span/><span/></div><div className="split-labels"><small>70% Train</small><small>15% Validation</small><small>15% Test</small></div></article><article className="panel research-detail"><div className="detail-icon"><BrainCircuit size={18}/></div><span className="step-label">MODEL ARCHITECTURE</span><h3>Four local checkpoints</h3><p>ResNet18, DenseNet121, EfficientNet-B0, and ResNeXt50_32x4d contribute to the ensemble output.</p><ul className="spec-list"><li><span>Input size</span><b>256 × 256</b></li><li><span>Aggregation</span><b>Mean probability</b></li><li><span>Label space</span><b>Five DR grades</b></li><li><span>Checkpoints</span><b>Local .pth weights</b></li></ul></article><article className="panel research-detail"><div className="detail-icon"><ScanEye size={18}/></div><span className="step-label">PREPROCESSING & XAI</span><h3>Analysis pipeline</h3><p>Results include the original, filtered inference image, and CLAHE green-channel view. Grad-CAM and SHAP are generated per model.</p><div className="capability"><span className="cap-dot ready"/> Grad-CAM <small>Per-model heatmaps</small></div><div className="capability"><span className="cap-dot ready"/> SHAP <small>Per-model attributions</small></div></article></div>
    <section className="section-block metrics-block"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-dot"/> EVALUATION</div><h2>Current research baseline</h2><p>Reported test-set metrics. These describe the research baseline only.</p></div><span className="metric-context"><ChartNoAxesCombined size={15}/> TEST SET</span></div><div className="metric-grid">{metrics.map(([value,label],i)=><article className="metric-card" key={label}><span className="metric-index">0{i+1}</span><strong>{value}</strong><small>{label}</small></article>)}</div></section>
    <section className="research-bottom"><article className="panel class-panel"><div className="panel-heading"><div><span className="step-label">LABEL SPACE</span><h2>Five ordinal grades</h2></div><Layers3 size={18}/></div><div className="class-list">{classes.map((name,i)=><div key={name}><span className={`class-number c${i}`}>{i}</span><strong>{name}</strong><span className="class-track"><i style={{width:`${20*(i+1)}%`}}/></span></div>)}</div><p className="table-note">Performance varies across severity grades; no per-class values are summarized here.</p></article><article className="panel limits-panel"><div className="panel-heading"><div><span className="step-label">INTERPRETATION</span><h2>Limitations in scope</h2></div><CircleAlert size={18}/></div><ul className="limitation-list"><li>Severe class imbalance affects minority-grade performance.</li><li>The current model is a research baseline; external validation is not integrated.</li><li>Calibration is under investigation.</li><li>The system has not been clinically validated.</li></ul></article></section>
    <section className="roadmap-section"><div className="roadmap-heading"><span className="eyebrow"><span className="eyebrow-dot"/> RESEARCH ROADMAP</span><h2>From baseline to broader evaluation.</h2><p>A planned sequence; later stages are future research work.</p></div><div className="roadmap-grid">{phases.map((phase,index)=><div className={`roadmap-step ${index===0?'roadmap-current':''}`} key={phase}><span>{String(index+1).padStart(2,'0')}</span><b>{phase}</b>{index<phases.length-1&&<ArrowDown size={13}/>}</div>)}</div></section><Disclaimer compact/>
  </div>;
}
